version: '3'

services:
  reverse-proxy:
    image: traefik:v2.9
    restart: always
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network
    labels:
      - "traefik.docker.network=traefik-network"

  service-one:
    build:
      context: ../base-microservice
    container_name: one
    restart: always
    networks:
      - traefik-network
    labels:
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.service-one.rule=Host(`service-one.docker.localhost`)"
      - "traefik.http.routers.service-one.middlewares=auth-success"
      - "traefik.http.middlewares.service-auth.forwardauth.address=http://service-auth:5000/api/v1.0.0/auth"
      - "traefik.http.middlewares.service-valid-one.forwardauth.address=http://service-valid-one:5000/api/v1.0.0/auth/headers"
      - "traefik.http.middlewares.service-valid-one.forwardauth.authResponseHeaders=CUSTOM-HEADER"
      - "traefik.http.middlewares.service-valid-two.forwardauth.address=http://service-valid-two:5000/api/v1.0.0/auth/headers"
      - "traefik.http.middlewares.service-valid-two.forwardauth.authResponseHeaders=CUSTOM-HEADER"
      - "traefik.http.middlewares.auth-success.chain.middlewares=service-auth,service-valid-one,service-valid-two"
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: 5000
      API_MESSAGE_RESPONSE: 'service-one'
    depends_on:
      - service-auth

  service-auth:
    build:
      context: ../base-microservice
    container_name: auth
    restart: always
    networks:
      - traefik-network
    labels:
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.service-auth.rule=Host(`service-auth.docker.localhost`)"
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: 5000
      API_MESSAGE_RESPONSE: 'service-auth'
    depends_on:
      - reverse-proxy

  service-valid-one:
    build:
      context: ../base-microservice
    container_name: valid-one
    restart: always
    networks:
      - traefik-network
    labels:
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.service-valid-one.rule=Host(`service-valid-one.docker.localhost`)"
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: 5000
      CUSTOM_HEADER: 'service-valid-one'
    depends_on:
      - reverse-proxy

  service-valid-two:
    build:
      context: ../base-microservice
    container_name: valid-two
    restart: always
    networks:
      - traefik-network
    labels:
      - "traefik.docker.network=traefik-network"
      - "traefik.http.routers.service-valid-two.rule=Host(`service-valid-two.docker.localhost`)"
    environment:
      API_HOST: '0.0.0.0'
      API_PORT: 5000
      CUSTOM_HEADER: 'service-valid-two'
    depends_on:
      - reverse-proxy

networks:
  traefik-network: